name: Test & Build

on:
  push:
    branches:
      - master
      - development
    tags:
      - v*
  pull_request:
    branches:
      - master
  release:
    types:
      - published
      - created
      - edited

jobs:
  job_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Python3.9 x64
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install docker-py
      - name: Start Redis Server
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 5.0
      - name: Run tests.py
        env:
          KEYDB_URL: $ {{ secrets.KEYDB_URL }}
        run: |
          python tests.py
  job_build:
    name: Publish docker image
    runs-on: ubuntu-latest
    needs: job_tests
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: docker.pkg.github.com
          repository: rigdenlab/conplot/conplot
          tags: latest
          dockerfile: .docker/Dockerfile
          push: true
          tag_with_ref: true
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: filosanrod/conplot
          tags: latest
          dockerfile: .docker/Dockerfile
          push: true
          tag_with_ref: true
